tar: build
	rm -rf _build/qubes-ssh-agent
	mkdir _build/qubes-ssh-agent
	cp dist/qubes-ssh-agent.xen dist/qubes-ssh-agent.xen.debug
	strip dist/qubes-ssh-agent.xen
	cp dist/qubes-ssh-agent.xen _build/qubes-ssh-agent/vmlinuz
	touch _build/qubes-ssh-agent/modules.img
	cat /dev/null | gzip > _build/qubes-ssh-agent/initramfs
	tar cjf qubes-ssh-agent.tar.bz2 -C _build qubes-ssh-agent
